titleAndCommits: true
types:
  - build
  - ci
  - docs
  - feat
  - fix
  - perf
  - refactor
  - release
  - test
  - chore
scopes:
  - '@blindnet/dci'
  - '@blindnet/prci'
  - '@blindnet/core'
  - '@blindnet-demos/devkit-simple-tutorial'
  - '@blindnet-demos/static'
allowMergeCommits: true
targetUrl: 'https://github.com/blindnet-io/privacy-components-web/blob/main/CONTRIBUTING.md#-commit-message-guidelines'
