name: Validate

on:
  pull_request:
    types: [opened, synchronize]
jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install dependencies 🔧
        run: |
          yarn install

      - name: Build 👷‍♀
        run: |
          yarn build

      - name: Check ✅
        run: |
          yarn lint
          yarn typecheck
          yarn test

      - name: Canary publish 📦
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          echo "@blindnet:registry=https://npm.pkg.github.com/blindnet-io" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc


          yarn lerna publish \
            --canary --yes --no-git-tag-version --no-push \
            --dist-tag pr${{ github.event.pull_request.number }} --preid pr${{ github.event.pull_request.number }} \
            --registry https://npm.pkg.github.com/blindnet-io
